export const SubscriptionTableHeaders = [
  { label: "#", className: "max-w-[20%]" },
  { label: "business", className: "max-w-[20%]" },
  { label: "plan", className: "max-w-[20%]" },
  { label: "Price", className: "max-w-[20%]" },
  { label: "Duration", className: "max-w-[20%]" },
  { label: "startDate", className: "max-w-[20%]" },
  { label: "endDate", className: "max-w-[20%]" },
  { label: "Remaining", className: "max-w-[20%]" },
  { label: "isActive/isExpired", className: "max-w-[20%]" },
  { label: "autoRenew", className: "max-w-[20%]" },
  { label: "Amount", className: "max-w-[20%]" },
  { label: "payment", className: "max-w-[20%]" },
  { label: "Created At", className: "max-w-[20%]" },
  { label: "Actions", className: "max-w-[20%]" },
];
